// === action types
export const SAVE_DESTINATIONS = 'SAVE_DESTINATIONS';
export const LOADING = 'LOADING';
export const HANDLE_FORM_OPENING_CLOSING = 'HANDLE_FORM_OPENING_CLOSING';
export const SAVE_DESTINATION_FORM = 'SAVE_DESTINATION_FORM';